name: tvCabinet_release

on:
  workflow_dispatch:
  push:
    tags: 'tvCabinet_v*.*.*'


jobs:
  create_release:
    runs-on: ubuntu-22.04
    steps:
      - name: setup
        run: sudo apt-get install -y freecad
    
      - name: checkout
        uses: actions/checkout@v3
    
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # tag_name is the same tag name that triggered this workflow
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: prepare files
        run: |
          echo "\
          from datetime import date
          document_name = \"tvCabinet\"
          FreeCAD.open(\"tvCabinet/\" + document_name + \".FCStd\")
          FreeCAD.setActiveDocument(document_name)
          t = FreeCAD.ActiveDocument.Template
          et = t.EditableTexts
          et[\"FC-Date\"] = date.today().strftime(\"%d.%m.%Y\")
          et[\"Drawing_number\"] = \"${{ github.ref_name }}, $(git rev-parse --short ${{ github.sha }})\"
          t.EditableTexts = et
          FreeCAD.ActiveDocument.save()"\
            > create_release.py
          cat create_release.py
          freecadcmd create_release.py
          
      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # this references to the step with id 'create_release'
          asset_path: ./tvCabinet/tvCabinet.FCStd
          asset_name: ${{ github.event.repository.name }}__${{ github.ref_name }}.FCStd
          asset_content_type: application/zip
